In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('train.csv')

In [5]:
df.head(32)

           Image_Label                                      EncodedPixels
0     0011165.jpg_Fish  264918 937 266318 937 267718 937 269118 937 27...
1   0011165.jpg_Flower  1355565 1002 1356965 1002 1358365 1002 1359765...
2   0011165.jpg_Gravel                                                NaN
3    0011165.jpg_Sugar                                                NaN
4     002be4f.jpg_Fish  233813 878 235213 878 236613 878 238010 881 23...
5   002be4f.jpg_Flower  1339279 519 1340679 519 1342079 519 1343479 51...
6   002be4f.jpg_Gravel                                                NaN
7    002be4f.jpg_Sugar  67495 350 68895 350 70295 350 71695 350 73095 ...
8     0031ae9.jpg_Fish  3510 690 4910 690 6310 690 7710 690 9110 690 1...
9   0031ae9.jpg_Flower  2047 703 3447 703 4847 703 6247 703 7647 703 9...
10  0031ae9.jpg_Gravel                                                NaN
11   0031ae9.jpg_Sugar  658170 388 659570 388 660970 388 662370 388 66...
12    0035239.jpg_Fish                                                NaN
13  0035239.jpg_Flower  100812 462 102212 462 103612 462 105012 462 10...
14  0035239.jpg_Gravel  65400 380 66800 380 68200 380 69600 380 71000 ...
15   0035239.jpg_Sugar                                                NaN
16    003994e.jpg_Fish  2367966 18 2367985 2 2367993 8 2368002 62 2369...
17  003994e.jpg_Flower                                                NaN
18  003994e.jpg_Gravel  353317 416 354717 416 356117 416 357517 416 35...
19   003994e.jpg_Sugar  28011 489 29411 489 30811 489 32211 489 33611 ...
20    00498ec.jpg_Fish                                                NaN
21  00498ec.jpg_Flower                                                NaN
22  00498ec.jpg_Gravel  326420 552 327820 552 329220 552 330620 552 33...
23   00498ec.jpg_Sugar                                                NaN
24    006bf7c.jpg_Fish  43614 529 45014 529 46414 529 47814 529 49214 ...
25  006bf7c.jpg_Flower                                                NaN
26  006bf7c.jpg_Gravel                                                NaN
27   006bf7c.jpg_Sugar  4221 185 5621 185 7021 185 8421 185 9821 185 1...
28    006c5a6.jpg_Fish  916291 381 917691 381 919091 381 920491 381 92...